### ISSUE TITLE
Wrong ownership of tpf-client configuration file

### ISSUE THREAD

**Issue by reduzent** [jschuett/tpf-jam-tool#5]
The tpf-reaper-tools writes a configuration file for tpf-client to `/Users/<user>/.tpf-client` so that tpf-client started from the tools is already configured with sensible settings for jamming. However, the user cannot change any settings afterwards, because the newly written configuration file is own by root:staff, thus the user has no permission to modify it. Ideally, the owership of the configuration file would be set to the user running the installer. I don't know if that's possible at all, though.

**Comment by jschuett** [comment]
I will try to adapt this for the next install.

**Comment by jschuett** [comment]
done
